# Generated by Django 6.1.1 on 2026-09-22 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quest_type', models.CharField(choices=[('daily', 'Daily'), ('one_time', 'One time'), ('habit', 'Habit')], max_length=20)),
                ('xp_reward', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='quests.questcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='quests.quest')),
            ],
        ),
        migrations.CreateModel(
            name='QuestStatReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_rewards', to='quests.quest')),
                ('stat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_rewards', to='core.stattype')),
            ],
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['user', 'is_active'], name='quests_ques_user_id_82726a_idx'),
        ),
        migrations.AddIndex(
            model_name='questcompletion',
            index=models.Index(fields=['quest', 'completed_at'], name='quests_ques_quest_i_7897cc_idx'),
        ),
    ]
