# Generated by Django 6.1.1 on 2026-09-29 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_length', models.PositiveIntegerField(default=0)),
                ('longest_length', models.PositiveIntegerField(default=0)),
                ('freezes_available', models.PositiveIntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('quest_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='quests.questcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'quest_category'), name='unique_user_quest_category_streak')],
            },
        ),
    ]
